#What block to use as the HaroTorch, this does not have to be a torch. Should include minecraft: prefix! Default: minecraft:torch
#I recommend you do not use non-transparent blocks. Particles will then not be seen, thus a Player cannot identify where their Torch is!
torchBlock: "minecraft:torch"

#Should there be particles around the Torch when it is placed in the world. Default: true
enableTorchParticles: true

#What should the range of the Torch be. Default: 64
torchRange: 64

#What radius should we use to highlight Torches. Default: 64
torchHighlightRange: 64

#For how long should the Torches be higlighted. In seconds. Default: 30
torchHighlightTime: 30

#How many 'rows' of particles should be spawned when a user uses /torch aoe. Default: 10
torchAoeParticleHeight: 10

activeLang: "en"

# Recipe for the Torch
#
# Example:
#
# recipeShape:
# - "xgx"
# - "gtx"
# - "xgx"
#
# recipeKeys:
# - "x<-->minecraft:air"
# - "g<-->minecraft:gold_ingot"
# - "t<-->minecraft:torch"
#
# It is really important that this formatting is correct!

recipeShape:
- "xgx"
- "gtx"
- "xgx"

recipeKeys:
- "x<-->minecraft:air"
- "g<-->minecraft:gold_ingot"
- "t<-->minecraft:torch"

#Should people be able to remove other people's torches. Default: false
allowRemoveNotOwnedTorch: false

#Should only hostile mobs be prevented from spawning. Default: true
#Note: Withers and Ender dragons are always spawnable
onlyBlockHostileMobs: true

# What mobs should be excluded from the block list
# Should NOT include minecraft: prefix!
#
# Example:
# 
# mobsExcludeFromBlockList:
# - "zombie"
# - "zombie_pigman"
#
# It is important that the format matches what Minecraft itself uses!
mobsExcludeFromBlockList:
